### PR TITLE
Clean_and_sorted_dataframe/contains csv and notebook

### PR DESCRIPTION
**Pull request by isha167**
Can you have a look and see if it is okay to merge in main?

### CODE REVIEW

**Comment by jimbleslilley** [comment]
Hi Isha, I think the file should be renamed, clean_dataframe doesn't tell us what is in the csv. Maybe something like "clean_specials.csv" or "clean_neflix_shows.csv" would be better?  

Other than that, great stuff as far as I can and I'll merge once done.

**Review by jimbleslilley — CHANGES_REQUESTED** [review]
Hi Isha, I think the file should be renamed, clean_dataframe doesn't tell us what is in the csv. Maybe something like "clean_specials.csv" or "clean_neflix_shows.csv" would be better?  

Other than that, great stuff as far as I can and I'll merge once done.

**Comment by isha167** [comment]
I will rename it and raise a review request.

**Review by jimbleslilley — APPROVED** [review]
name changed, looks good!

**Pull request merged**
